Fix signal stuff (#15)

diff --git a/rootfs/etc/run_tests b/rootfs/etc/run_tests
--- a/rootfs/etc/run_tests
+++ b/rootfs/etc/run_tests
@@ -1,138 +1,29 @@
 #!/bin/sh
+# Many os-tests opendir(".") and expect a subdirectory named after the suite
+# (e.g. dirent/readdir looks for "./dirent"). Run from /bin/os-tests-sortix.
+
 echo "========================================="
 echo "  os-tests-sortix"
 echo "========================================="
-/bin/os-tests-sortix/fcntl/open
-/bin/os-tests-sortix/signal/kill
-/bin/os-tests-sortix/signal/sigaddset
-/bin/os-tests-sortix/signal/sigdelset
-/bin/os-tests-sortix/signal/sigemptyset
-/bin/os-tests-sortix/signal/sigfillset
-/bin/os-tests-sortix/signal/sigismember
-/bin/os-tests-sortix/stdatomic/atomic_flag_clear
-/bin/os-tests-sortix/stdatomic/atomic_flag_clear_explicit
-/bin/os-tests-sortix/stdatomic/atomic_flag_test_and_set
-/bin/os-tests-sortix/stdatomic/atomic_flag_test_and_set_explicit
-/bin/os-tests-sortix/stdatomic/atomic_signal_fence
-/bin/os-tests-sortix/stdatomic/atomic_thread_fence
-/bin/os-tests-sortix/stdio/asprintf
-/bin/os-tests-sortix/stdio/clearerr
-/bin/os-tests-sortix/stdio/dprintf
-/bin/os-tests-sortix/stdio/fclose
-/bin/os-tests-sortix/stdio/fdopen
-/bin/os-tests-sortix/stdio/feof
-/bin/os-tests-sortix/stdio/ferror
-/bin/os-tests-sortix/stdio/fflush
-/bin/os-tests-sortix/stdio/fgetc
-/bin/os-tests-sortix/stdio/fgetpos
-/bin/os-tests-sortix/stdio/fgets
-/bin/os-tests-sortix/stdio/fileno
-/bin/os-tests-sortix/stdio/flockfile
-/bin/os-tests-sortix/stdio/fmemopen
-/bin/os-tests-sortix/stdio/fopen
-/bin/os-tests-sortix/stdio/fprintf
-/bin/os-tests-sortix/stdio/fputc
-/bin/os-tests-sortix/stdio/fputs
-/bin/os-tests-sortix/stdio/fread
-/bin/os-tests-sortix/stdio/fscanf
-/bin/os-tests-sortix/stdio/fseek
-/bin/os-tests-sortix/stdio/fsetpos
-/bin/os-tests-sortix/stdio/ftell
-/bin/os-tests-sortix/stdio/ftrylockfile
-/bin/os-tests-sortix/stdio/funlockfile
-/bin/os-tests-sortix/stdio/fwrite
-/bin/os-tests-sortix/stdio/printf
-/bin/os-tests-sortix/stdio/rename
-/bin/os-tests-sortix/stdio/rewind
-/bin/os-tests-sortix/stdio/scanf
-/bin/os-tests-sortix/stdio/snprintf
-/bin/os-tests-sortix/stdio/sprintf
-/bin/os-tests-sortix/stdio/sscanf
-/bin/os-tests-sortix/stdio/tmpfile
-/bin/os-tests-sortix/stdio/ungetc
-/bin/os-tests-sortix/stdio/vasprintf
-/bin/os-tests-sortix/stdio/vdprintf
-/bin/os-tests-sortix/stdio/vfprintf
-/bin/os-tests-sortix/stdio/vfscanf
-/bin/os-tests-sortix/stdio/vprintf
-/bin/os-tests-sortix/stdio/vscanf
-/bin/os-tests-sortix/stdio/vsnprintf
-/bin/os-tests-sortix/stdio/vsprintf
-/bin/os-tests-sortix/stdio/vsscanf
-/bin/os-tests-sortix/stdlib/_Exit
-/bin/os-tests-sortix/stdlib/atexit
-/bin/os-tests-sortix/stdlib/atoi
-/bin/os-tests-sortix/stdlib/calloc
-/bin/os-tests-sortix/stdlib/exit
-/bin/os-tests-sortix/stdlib/free
-/bin/os-tests-sortix/stdlib/malloc
-/bin/os-tests-sortix/stdlib/mkstemp
-/bin/os-tests-sortix/string/memccpy
-/bin/os-tests-sortix/string/memchr
-/bin/os-tests-sortix/string/memcmp
-/bin/os-tests-sortix/string/memcpy
-/bin/os-tests-sortix/string/memmem
-/bin/os-tests-sortix/string/memmove
-/bin/os-tests-sortix/string/memset
-/bin/os-tests-sortix/string/stpcpy
-/bin/os-tests-sortix/string/stpncpy
-/bin/os-tests-sortix/string/strcat
-/bin/os-tests-sortix/string/strchr
-/bin/os-tests-sortix/string/strcmp
-/bin/os-tests-sortix/string/strcoll
-/bin/os-tests-sortix/string/strcoll_l
-/bin/os-tests-sortix/string/strcpy
-/bin/os-tests-sortix/string/strcspn
-/bin/os-tests-sortix/string/strdup
-/bin/os-tests-sortix/string/strerror
-/bin/os-tests-sortix/string/strerror_l
-/bin/os-tests-sortix/string/strerror_r
-/bin/os-tests-sortix/string/strlcat
-/bin/os-tests-sortix/string/strlcpy
-/bin/os-tests-sortix/string/strlen
-/bin/os-tests-sortix/string/strncat
-/bin/os-tests-sortix/string/strncmp
-/bin/os-tests-sortix/string/strncpy
-/bin/os-tests-sortix/string/strndup
-/bin/os-tests-sortix/string/strnlen
-/bin/os-tests-sortix/string/strpbrk
-/bin/os-tests-sortix/string/strrchr
-/bin/os-tests-sortix/string/strsignal
-/bin/os-tests-sortix/string/strspn
-/bin/os-tests-sortix/string/strstr
-/bin/os-tests-sortix/string/strtok
-/bin/os-tests-sortix/string/strtok_r
-/bin/os-tests-sortix/string/strxfrm
-/bin/os-tests-sortix/string/strxfrm_l
-/bin/os-tests-sortix/strings/strcasecmp
-/bin/os-tests-sortix/strings/strncasecmp
-/bin/os-tests-sortix/sys_stat/chmod
-/bin/os-tests-sortix/sys_stat/fstat
-/bin/os-tests-sortix/sys_stat/lstat
-/bin/os-tests-sortix/sys_stat/mkdir
-/bin/os-tests-sortix/sys_stat/stat
-/bin/os-tests-sortix/time/nanosleep
-/bin/os-tests-sortix/unistd/chdir
-/bin/os-tests-sortix/unistd/close
-/bin/os-tests-sortix/unistd/dup2
-/bin/os-tests-sortix/unistd/execl
-/bin/os-tests-sortix/unistd/execv
-/bin/os-tests-sortix/unistd/fork
-/bin/os-tests-sortix/unistd/fsync
-/bin/os-tests-sortix/unistd/ftruncate
-/bin/os-tests-sortix/unistd/getcwd
-/bin/os-tests-sortix/unistd/getopt
-/bin/os-tests-sortix/unistd/getpid
-/bin/os-tests-sortix/unistd/getppid
-/bin/os-tests-sortix/unistd/lseek
-/bin/os-tests-sortix/unistd/pipe
-/bin/os-tests-sortix/unistd/read
-/bin/os-tests-sortix/unistd/readlink
-/bin/os-tests-sortix/unistd/rmdir
-/bin/os-tests-sortix/unistd/sleep
-/bin/os-tests-sortix/unistd/symlink
-/bin/os-tests-sortix/unistd/truncate
-/bin/os-tests-sortix/unistd/unlink
-/bin/os-tests-sortix/unistd/write
+
+if [ ! -d /bin/os-tests-sortix ]; then
+echo "missing /bin/os-tests-sortix (run: make -C thirdparty os-tests-install)"
+exit 1
+fi
+
+cd /bin/os-tests-sortix
+./dirent/alphasort
+./dirent/closedir
+./dirent/dirfd
+./dirent/fdopendir
+./dirent/opendir
+./dirent/posix_getdents
+./dirent/readdir
+./dirent/readdir_r
+./dirent/rewinddir
+./dirent/scandir
+./dirent/seekdir
+./dirent/telldir
+
 echo "========================================="
 echo "  Done"
